### ISSUE TITLE
Aniyomi extensions don't work

### ISSUE THREAD

**Issue by KillerDogeEmpire** [CranberrySoup/AniyomiCompatExtension#1]
Some aniyomi extensions work in aniyomi but just show no link found on cloudstream or an okhttp error, and how can i use twitch ?😭

**Comment by KillerDogeEmpire** [comment]
Oh, forgot some sources say remote error and then says no link found, but works in aniyomi

**Comment by KillerDogeEmpire** [comment]
Nine of the multi language extensions work in cs3

**Comment by KillerDogeEmpire** [comment]
It just doesn't show up

**Comment by KillerDogeEmpire** [comment]
My bad got the all sources showing along with twitch, but still issues with the extensions working on aniyomi but either showing remote source error, and then no links found, and the okhttp error

**Comment by CranberrySoup** [comment]
Please give more info if you want this fixed

**Comment by KillerDogeEmpire** [comment]
Sorry for late response, but it's been fixed @CranberrySoup
