### ISSUE TITLE
(Yomiroll) add language in preferred option

### ISSUE THREAD

**Issue by Shoaib12564** [CranberrySoup/AniyomiCompatExtension#22]
Source name
Yomiroll

Source language

Describe your suggested feature

add the multi-language language  options 

Like aniyomi app 

![Screenshot_20231126-141544_Kuukiyomi](https://github.com/CranberrySoup/AniyomiCompatExtension/assets/149332844/a5ad087e-1d04-4af5-a64e-5087c58fd514)
![Screenshot_20231126-141551_Kuukiyomi](https://github.com/CranberrySoup/AniyomiCompatExtension/assets/149332844/3358fc51-351e-470a-8ed7-f95a375d3304)

**Comment by CranberrySoup** [comment]
Preferences exists in the latest Aniyomi Compat version.
