### ISSUE TITLE
Search not working in CS3

### ISSUE THREAD

**Issue by jeybsss** [CranberrySoup/AniyomiCompatExtension#25]
KickAssAnime and AllAnimeChi search in cs3 seems to be not working

KickAss seems to be also not working in CS3 because the episodes show no links found. But AllAnimeChi works expect the search.

Android version: 22

![Screenshot_2023-12-10-18-51-01-25_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/CranberrySoup/AniyomiCompatExtension/assets/88224473/ef690b13-b777-4346-970d-505ed02dbf76)

**Comment by jeybsss** [comment]
![Screenshot_2023-12-10-18-58-17-37_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/CranberrySoup/AniyomiCompatExtension/assets/88224473/cb9601d9-ba8e-49c1-a44f-92bfb2a5633f)

**Comment by CranberrySoup** [comment]
Fixed in 1.1.1
