### ISSUE TITLE
animeSAGA extension is not working 

### ISSUE THREAD

**Issue by kusokohei** [CranberrySoup/AniyomiCompatExtension#27]
![Screenshot_2024-01-04-02-38-19-810_com lagradost cloudstream3](https://github.com/CranberrySoup/AniyomiCompatExtension/assets/140593165/3a5a2b0e-ec0e-4648-a7ca-8f02f231ddbc)

The server response is no links found and with a VPN it's still gives the same response
Please fix this

**Comment by HaxerAhmed** [comment]
Use beta version of this app
