### ISSUE TITLE
Extensions Not Showing up

### ISSUE THREAD

**Issue by LyuboA31** [CranberrySoup/AniyomiCompatExtension#3]
AnimeXin, LMAnime and Yamiroll extension don't show up at all and Animension links don't work all 4 extensions work fine in Aniyomi
can you please fix them
Thanks

**Comment by CranberrySoup** [comment]
AnimeXin, LMAnime, Yamiroll and Animension works as of the latest update.
If they do not show up it is likely a matter of your language preferences in CloudStream not this extension.

**Comment by LyuboA31** [comment]
Animexin now shows up but OK.ru, Gdrive and some other links do Not work Only Doodstream and Dailymotion (All Sub Player Old) work
while all links work in Aniyomi 
LMAnime, Yamiroll and Animension all work
Thanks

**Comment by LyuboA31** [comment]
Doupo Cangqiong season 5 episode 1
it's other name on Animexin is
Battle Through the Heavens again season 5 episode 1
and
Apotheosis it's other name is Bai Lian Cheng Shen

**Comment by CranberrySoup** [comment]
OK.ru is confirmed not working.
Gdrive is inconsistent in the Aniyomi app, working sometimes and sometimes not which makes it hard to test.
Hopefully it will be fixed when I manage to fix OK.ru.

**Comment by LyuboA31** [comment]
Thanks for all your hard work man
i have a strange issues there are two new Aniyomi extensions Luciferdonghua and Donghuastream both showed up no problems both work on my phone but both don't work on my TV just show No Links Found when trying to start something i will try reinstalling CloudStream maybe that will help

**Comment by CranberrySoup** [comment]
OK.ru is fixed, Gdrive is broken in and of itself.
