### ISSUE TITLE
number of extension:0

### ISSUE THREAD

**Issue by Kraptor123** [CranberrySoup/AniyomiCompatExtension#6]
Android 13
No extensions
I tried also on my android TV it shows the extension but can't watch anything

**Comment by CranberrySoup** [comment]
Very likely duplicate of: https://github.com/CranberrySoup/AniyomiCompatExtension/issues/7
Send a screenshot of your AniyomiCompat Plugin settings like in #7 and I will be able to diagnose the issue.

**Comment by Mollomm1** [comment]
Update manually https://github.com/recloudstream/cloudstream/releases/download/pre-release/app-prerelease-release.apk it worked for me.

**Comment by Kraptor123** [comment]
![Screenshot_2023-09-02-20-17-52-746_com lagradost cloudstream3](https://github.com/CranberrySoup/AniyomiCompatExtension/assets/89366989/fcf9d34c-f066-4292-8f8a-76eb7a067bad)
![Screenshot_2023-09-02-20-17-47-482_com lagradost cloudstream3](https://github.com/CranberrySoup/AniyomiCompatExtension/assets/89366989/53863019-36af-47fc-b0c2-3e15b4eac084)

**Comment by Kraptor123** [comment]
![Uploading Screenshot_2023-09-02-20-17-52-746_com.lagradost.cloudstream3.jpg…]()


> Update manually https://github.com/recloudstream/cloudstream/releases/download/pre-release/app-prerelease-release.apk it worked for me.

Yeah that worked thank you very much!
