### ISSUE TITLE
Number of Extension: 0 (Cloudstream 4.0.1)

### ISSUE THREAD

**Issue by KaguyaUchiha** [CranberrySoup/AniyomiCompatExtension#8]
![Screenshot_2023-09-02-10-18-04-105_com lagradost cloudstream3](https://github.com/CranberrySoup/AniyomiCompatExtension/assets/112609547/064cbad2-628e-4fdb-b96f-2ad853db503c)

I'm getting the issue of Number of extension: 0 even when i followed everything mentioned

Also somewhere i saw a comment to try thr extension on cloudstream beta..

So i tried that as well

The thing is this Aniyomi Compat extension is working on cloudstream beta but it isn't working on cloudstream version 4.0.1.

I really don't want to switch to the beta since its a bit buggy for me

Also i will lose access to all my download directly from the app

Kindly try to fix the bug with the extension in cloudstream 4.0.1

Thank You :)

**Comment by CranberrySoup** [comment]
Not possible to fix it on the stable before next release.
